import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Award, CalendarCheck, Gauge, Map, Target, Trophy } from "lucide-react";
import { DemoBadge, InsightCard, LineChartCard, MetricCard, PageIntro, Segmented } from "@/components/sports-ui";
import { progression, runTrend, weekly } from "@/lib/sports-data";
export const Route=createFileRoute("/athlete-performance")({head:()=>({meta:[{title:"Athlete Performance — SportsMax"},{name:"description",content:"Explore a demo athlete profile with progress, consistency, pace, distance, and heart-rate performance trends."},{property:"og:title",content:"Athlete Performance — SportsMax"},{property:"og:description",content:"Understand an athlete's complete performance story."},{property:"og:type",content:"profile"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/athlete-performance"}]}),component:AthletePerformance});
function AthletePerformance(){
  const [range, setRange] = useState("30 Days");
  return <><PageIntro eyebrow="Athlete intelligence" title="Every session tells part of the story." text="Follow progress across pace, volume, effort, and consistency with a complete athlete performance view." action={<div className="flex flex-col items-end gap-3"><DemoBadge/><Segmented values={["7 Days","30 Days","90 Days","All time"]} value={range} onChange={setRange}/></div>}/><section className="py-12"><div className="content-wrap"><div className="surface-card grid gap-6 p-6 md:grid-cols-[auto_1fr_auto] md:items-center"><div className="grid h-20 w-20 place-items-center rounded-full bg-gradient-to-br from-primary to-accent text-2xl font-bold text-primary-foreground glow-sm">AM</div><div><div className="flex flex-wrap items-center gap-3"><h2 className="text-2xl font-semibold">Alex Mercer</h2><span className="rounded-full border border-primary/30 bg-primary/10 px-2.5 py-1 text-xs font-semibold text-primary">Advanced runner</span><span className="text-xs text-muted-foreground">Range: {range}</span></div><p className="mt-2 text-sm text-muted-foreground">Road & trail running · Goal: Sub-40 minute 10K</p></div><div className="grid grid-cols-2 gap-6 text-right"><div><p className="text-2xl font-semibold">84</p><p className="text-xs text-muted-foreground">Total sessions</p></div><div><p className="text-2xl font-semibold">624 km</p><p className="text-xs text-muted-foreground">Total distance</p></div></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><MetricCard label="Current performance" value="88 / 100" note="Excellent" trend="up" icon={<Gauge/>}/><MetricCard label="Weekly progress" value="+3.2%" note="On target" trend="up" icon={<Target/>}/><MetricCard label="Monthly progress" value="+8.6%" note="Ahead of goal" trend="up" icon={<Map/>}/><MetricCard label="Personal best" value="41:54" note="10K · recent" icon={<Trophy/>}/><MetricCard label="Consistency" value="91%" note="12-week high" trend="up" icon={<CalendarCheck/>}/></div><div className="mt-5 grid gap-5 lg:grid-cols-2"><LineChartCard title="Pace improvement" data={runTrend} keys={["pace"]} unit=" /km"/><LineChartCard title="Distance progression" data={weekly} keys={["distance"]} unit=" km"/><LineChartCard title="Heart-rate trend" data={runTrend} keys={["heart"]} unit=" bpm"/><LineChartCard title="Training frequency" data={progression} keys={["consistency"]} unit="%"/></div><div className="mt-5 grid gap-5 lg:grid-cols-[1fr_auto] lg:items-stretch"><InsightCard type="Performance insight" title="Pace is improving without increased strain" detail="Average pace has improved over the last four weeks while training volume and heart-rate effort have remained consistent." metric="High confidence"/><div className="surface-card grid min-w-64 place-items-center p-7 text-center"><Award className="h-9 w-9 text-primary"/><p className="mt-4 font-semibold">Monthly standout</p><p className="mt-1 text-sm text-muted-foreground">Top 8% for consistency</p></div></div></div></section></>;}
