import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Activity, Gauge, Map, TrendingUp, Users } from "lucide-react";
import { AreaChartCard, BarChartCard, DemoBadge, MetricCard, PageIntro, Segmented } from "@/components/sports-ui";
import { athletes, progression, weekly } from "@/lib/sports-data";
export const Route=createFileRoute("/dashboard")({head:()=>({meta:[{title:"Analytics Dashboard — SportsMax"},{name:"description",content:"Monitor athletes, sessions, distance, pace, and performance improvement in one sports analytics dashboard."},{property:"og:title",content:"Analytics Dashboard — SportsMax"},{property:"og:description",content:"A professional demo dashboard for sports performance intelligence."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/dashboard"}]}),component:Dashboard});
function Dashboard(){
  const [period,setPeriod]=useState("Monthly");
  const [sport,setSport]=useState("All Sports");
  return <><PageIntro eyebrow="Organization analytics" title="Performance at a glance." text="Monitor activity, compare athlete progress, and surface the signals that matter across your program." action={<div className="flex flex-col items-end gap-3"><DemoBadge/><Segmented values={["Weekly","Monthly","Yearly"]} value={period} onChange={setPeriod}/></div>}/><section className="py-12"><div className="content-wrap"><div className="mb-6 flex flex-wrap items-center justify-between gap-4"><div className="flex flex-wrap items-center gap-2"><Segmented values={["All Sports","Running","Track & Field","Cross Country"]} value={sport} onChange={setSport}/></div><span className="text-xs text-muted-foreground">Showing 5 active athletes · {period} aggregate</span></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><MetricCard label="Active athletes" value="248" note="+12 this month" trend="up" icon={<Users/>}/><MetricCard label="Total sessions" value="1,842" note={period} icon={<Activity/>}/><MetricCard label="Total distance" value="12,406 km" note="+9.4%" trend="up" icon={<Map/>}/><MetricCard label="Average pace" value="5:24 /km" note="12 sec faster" trend="up" icon={<Gauge/>}/><MetricCard label="Improvement" value="+8.6%" note="Program average" trend="up" icon={<TrendingUp/>}/></div><div className="mt-5 grid gap-5 lg:grid-cols-2"><AreaChartCard title="Performance trend" data={progression}/><BarChartCard title="Weekly activity" subtitle="Distance completed across all active athletes" data={weekly}/></div><div className="mt-5 surface-card overflow-hidden"><div className="flex items-center justify-between border-b border-border p-5"><div><h2 className="font-semibold">Athlete performance table</h2><p className="mt-1 text-xs text-muted-foreground">Current period · {period} · {sport}</p></div><DemoBadge/></div><div className="overflow-x-auto"><table className="w-full min-w-[660px] text-left text-sm"><thead className="bg-secondary text-xs uppercase tracking-wider text-muted-foreground"><tr>{["Athlete","Sessions","Distance","Avg pace","Progress"].map(x=><th key={x} className="px-5 py-3 font-semibold">{x}</th>)}</tr></thead><tbody>{athletes.map(a=><tr key={a.name} className="border-t border-border transition hover:bg-secondary/40"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-primary/15 text-xs font-bold text-primary">{a.initials}</span><span className="font-medium">{a.name}</span></div></td><td className="px-5 py-4 text-muted-foreground">{a.sessions}</td><td className="px-5 py-4 text-muted-foreground">{a.distance}</td><td className="px-5 py-4 font-mono">{a.pace}</td><td className="px-5 py-4 font-semibold trend-up">{a.progress}</td></tr>)}</tbody></table></div></div></div></section></>;}
